### ISSUE TITLE
initializePostgresqlEventStore only initialises Eventful's default table

### ISSUE THREAD

**Issue by ch3pjw** [jdreaver/eventful#20]
`Eventful.Store.Postgresql.initializePostgresqlEventStore` assumes that you're using the `events` table/migration definition defined in `Eventful.Store.Sql.DefaultEntity`. However, I'm trying to migrate event definitions from one serialisation to another, and so I've got an `events_2` table that I now want to switch over to be my primary event log.

I know that `initializePostgresqlEventStore` is simple - just running a standard `Persistent` migration - so there's an argument that I should just write my own if I'm going off the beaten track. But, it seems a little weird to define an `SqlEventStoreConfig` data type that lets you specify how to write log entries, whilst missing out how to create the table.

I propose that `SqlEventStoreConfig` be extended to encapsulate the migration function, and that  `initializePostgresqlEventStore` take an additional `SqlEventStoreConfig` argument so that it can extract the migration appropriate to the config.

Thoughts?

Happy to write a PR if that sounds like a good plan.

**Comment by jdreaver** [comment]
To be totally honest I'm not a huge fan of that function. I think I just created it to make testing easier. Indeed it's only used in `PostgresqlSpec.hs`. Lots of folks don't like using `persistent`'s migration mechanism (myself included), especially in production.

I'm actually planning on just removing it altogether, because indeed it is weird that it exists in the first place if it isn't going to use `SqlEventStoreConfig`.

Thanks for bringing this up! I can see how this function is a little undesirable as-is. Is it okay for you to manually use `persistent`'s migration mechanism for now?

**Comment by ch3pjw** [comment]
Already am ;-)

Perhaps I could move it into the tests then?

**Comment by jdreaver** [comment]
Heh, I got ahead of myself and already did it https://github.com/jdreaver/eventful/commit/920783d779b2322a77450488ee473050923ce3d3
